# Generated by Django 5.2.5 on 2025-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='touristinquiry',
            name='full_name',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='touristinquiry',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='touristinquiry',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
