# Generated by Django 5.2.5 on 2025-08-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='preferred_country',
            field=models.CharField(choices=[('poland', 'Poland'), ('northern_cyprus', 'Northern Cyprus'), ('denmark', 'Denmark')], default=1, help_text='Your preferred study destination', max_length=20),
            preserve_default=False,
        ),
    ]
