# Generated by Django 5.2.5 on 2025-08-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_studentapplication_preferred_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristinquiry',
            name='destination',
        ),
        migrations.AddField(
            model_name='touristinquiry',
            name='destination_details',
            field=models.CharField(blank=True, help_text="Specific cities or attractions you'd like to visit", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touristinquiry',
            name='preferred_destination',
            field=models.CharField(choices=[('zambia', 'Zambia'), ('ghana', 'Ghana'), ('eswatini', 'Eswatini'), ('zimbabwe', 'Zimbabwe'), ('china', 'China'), ('dubai', 'Dubai, UAE'), ('nigeria', 'Nigeria')], default=1, help_text='Your preferred travel destination', max_length=20),
            preserve_default=False,
        ),
    ]
