# Generated by Django 5.2.5 on 2025-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_touristinquiry_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slide_type', models.CharField(choices=[('student', 'Student Slide'), ('tourist', 'Tourist Slide')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['slide_type'],
            },
        ),
    ]
