# Generated by Django 5.2.5 on 2025-08-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_flag', models.CharField(blank=True, help_text='Emoji flag or leave blank', max_length=10)),
                ('description', models.TextField()),
                ('tuition_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('living_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('scholarship_title', models.CharField(blank=True, max_length=200, null=True)),
                ('scholarship_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouristDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_flag', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('attraction_1', models.CharField(blank=True, max_length=200, null=True)),
                ('attraction_2', models.CharField(blank=True, max_length=200, null=True)),
                ('attraction_3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_destinations/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.studentdestination')),
            ],
        ),
        migrations.CreateModel(
            name='TouristDestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourist_destinations/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.touristdestination')),
            ],
        ),
    ]
