# Generated by Django 5.2.5 on 2025-08-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_studentdestination_touristdestination_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
        migrations.RemoveField(
            model_name='studentdestinationimage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='touristdestinationimage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='touristinquiry',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='StudentApplication',
        ),
        migrations.DeleteModel(
            name='StudentDestination',
        ),
        migrations.DeleteModel(
            name='StudentDestinationImage',
        ),
        migrations.DeleteModel(
            name='TouristDestination',
        ),
        migrations.DeleteModel(
            name='TouristDestinationImage',
        ),
        migrations.DeleteModel(
            name='TouristInquiry',
        ),
    ]
