# Generated by Django 5.2.5 on 2025-08-22 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slide_type', models.CharField(choices=[('student', 'Student Slide'), ('tourist', 'Tourist Slide')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['slide_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_flag', models.CharField(blank=True, help_text='Emoji flag or leave blank', max_length=10)),
                ('description', models.TextField()),
                ('tuition_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('living_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('scholarship_title', models.CharField(blank=True, max_length=200, null=True)),
                ('scholarship_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouristDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_flag', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('attraction_1', models.CharField(blank=True, max_length=200, null=True)),
                ('attraction_2', models.CharField(blank=True, max_length=200, null=True)),
                ('attraction_3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('study_level', models.CharField(choices=[('Postgraduate', 'Postgraduate'), ('Undergraduate', 'Undergraduate')], max_length=20)),
                ('preferred_country', models.CharField(choices=[('poland', 'Poland'), ('northern_cyprus', 'Northern Cyprus'), ('denmark', 'Denmark')], help_text='Your preferred study destination', max_length=20)),
                ('course_of_interest', models.CharField(max_length=255)),
                ('passport_or_nrc', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_destinations/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='student_travel.studentdestination')),
            ],
        ),
        migrations.CreateModel(
            name='TouristDestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourist_destinations/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='student_travel.touristdestination')),
            ],
        ),
        migrations.CreateModel(
            name='TouristInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_destination', models.CharField(choices=[('zambia', 'Zambia'), ('ghana', 'Ghana'), ('eswatini', 'Eswatini'), ('zimbabwe', 'Zimbabwe'), ('china', 'China'), ('dubai', 'Dubai, UAE'), ('nigeria', 'Nigeria')], help_text='Your preferred travel destination', max_length=20)),
                ('destination_details', models.CharField(blank=True, help_text="Specific cities or attractions you'd like to visit", max_length=255, null=True)),
                ('travel_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
