# Generated by Django 5.2.5 on 2025-08-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristdestination',
            name='attraction_1',
        ),
        migrations.RemoveField(
            model_name='touristdestination',
            name='attraction_2',
        ),
        migrations.RemoveField(
            model_name='touristdestination',
            name='attraction_3',
        ),
        migrations.AddField(
            model_name='touristinquiry',
            name='attraction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristdestination',
            name='country_flag',
            field=models.CharField(blank=True, help_text='Emoji or leave blank', max_length=10),
        ),
        migrations.CreateModel(
            name='AttractionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='student_travel.touristdestination')),
            ],
        ),
        migrations.CreateModel(
            name='AttractionSiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attraction_sites/')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='student_travel.attractionsite')),
            ],
        ),
    ]
